export const EXAMPLES = [
  {
    name: 'Buffer Fill',
    description: 'Zero-overhead pointer + register parameter passing',
    source: `fn fill(buffer: *u8, value: u8, count: u16) {
    while count > 0 {
        count--;
        buffer[count] = value;
    }
}
`,
  },
  {
    name: 'Hello Registers',
    description: 'Register binding and function basics',
    source: `// R65 Playground — Register binding example
//
// Functions bind parameters directly to CPU registers.
// No stack frames, no calling convention overhead.

#[zeropage]
static mut COUNTER: u8;

fn add_offset(value @ A: u8, offset @ X: u16) -> u8 {
    COUNTER++;
    let result @ A = A + 1;
    return result;
}

fn reset_counter() {
    COUNTER = 0;
}
`,
  },
  {
    name: 'Match Expression',
    description: 'match arms, wildcard, and match used as a value',
    source: `// match is both a statement and an expression.
//
// Arms accept literals, ranges (0..=9), and or-patterns
// (1 | 2 | 3). A wildcard _ is required unless the arms
// already cover every value.

fn classify(val @ A: u8) -> u8 {
    let result: u8 = match val {
        0 => 10,
        1 => 20,
        _ => 30,
    };
    return result;
}
`,
  },
  {
    name: 'Expression Blocks',
    description: 'if and { } blocks are expressions — implicit tail returns',
    source: `// The last expression in a block becomes its value, so
// if/else can be used directly as a return value or a
// let-binding initializer — no 'return' keyword needed.

fn abs_diff(a: u8, b: u8) -> u8 {
    if a > b { a - b } else { b - a }
}

fn clamp_hi(v: u8) -> u8 {
    let capped: u8 = if v > 100 { 100 } else { v };
    return capped;
}
`,
  },
  {
    name: 'Struct Pointers',
    description: 'Packed structs with field access through a pointer',
    source: `// Structs are packed (no padding) and passed by pointer.
// Field access through the pointer compiles to indexed
// loads/stores — no hidden copies.

struct Entity {
    kind: u8,
    health: u16,
}

#[ram]
static mut ENEMY: Entity = Entity { kind: 1, health: 50 };

fn damage(e: *Entity, amount: u8) {
    e.health = e.health - (amount as u16);
}

fn heal_full(e: *Entity) {
    e.health = 100;
}
`,
  },
  {
    name: 'Trait Dispatch',
    description: 'Dynamic dispatch through dyn trait objects',
    source: `// Traits give you runtime polymorphism. A *dyn pointer
// carries a TypeId; method calls dispatch through a jump
// table generated by the compiler.

struct Player { x: u8, y: u8 }
struct Enemy { x: u8, y: u8, hp: u8 }

trait Drawable { fn draw(*self); }

impl Drawable for Player {
    fn draw(*self) { RESULT = 42; }
}
impl Drawable for Enemy {
    fn draw(*self) { RESULT = 99; }
}

#[zeropage(0x10)]
static mut RESULT: u8;
#[lowram]
static mut PLAYER: Player = Player { x: 8, y: 8 };
#[lowram]
static mut ENEMY: Enemy = Enemy { x: 0, y: 0, hp: 10 };

#[entry]
fn main() {
    let d: *dyn Drawable = &ENEMY;
    d.draw();
}
`,
  },
  {
    name: 'Multi-Return',
    description: 'Returning multiple values in registers (rA, rB)',
    source: `// Functions can return several values at once, each in a
// named register. The B register is the high byte of the
// accumulator, free to use in 8-bit mode.

#[zeropage(0x10)]
static mut LO: u8;
#[zeropage(0x11)]
static mut HI: u8;

fn add_and_keep(lo @ A: u8, hi @ B: u8) -> rA, rB {
    A = lo + 1;
    return A, B;
}

#[entry]
fn main() {
    let mut a_val: u8;
    let mut b_val: u8;
    a_val, b_val = add_and_keep(0x10, 0x55);
    LO = a_val;
    HI = b_val;
}
`,
  },
  {
    name: 'Register Preservation',
    description: '#[preserves] auto-saves and restores registers',
    source: `// #[preserves(...)] tells the compiler to save and restore
// the listed registers around the function body, so callers
// see them unchanged even though the body clobbers them.

#[preserves(X)]
fn process(val @ A: u8) -> u8 {
    X = 999;        // saved on entry, restored on exit
    A = val + 1;
    return A;
}

#[entry]
fn main() {
    X = 0x42;
    A = process(10);   // X is still 0x42 afterward
}
`,
  },
  {
    name: 'Casts & Cost Model',
    description: 'Explicit as casts and power-of-2 multiply',
    source: `// All conversions are explicit via 'as'. The * operator
// only accepts power-of-2 constants because it compiles to
// bit shifts — here val * 2 becomes a single ASL.

fn double_wide(val: u8) -> u16 {
    let wide: u16 = val as u16 * 2;
    return wide;
}
`,
  },
  {
    name: 'Compile-Time Table',
    description: 'const fn builds a lookup table at compile time',
    source: `// const fn runs at compile time. The squares table below
// is fully computed during compilation and baked into ROM —
// zero runtime cost to build it.

const fn build_squares() -> [u16; 16] {
    let mut t: [u16; 16] = [0; 16];
    for i in 0..16 {
        t[i] = (i as u16) * (i as u16);
    }
    return t;
}

static SQUARES: [u16; 16] = build_squares();

#[zeropage(0x10)]
static mut RESULT: u16;

#[entry]
fn main() {
    RESULT = SQUARES[5];   // 25, computed at compile time
}
`,
  },
];
